practices/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView
from practices import views, models

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(queryset = models.Subject.objects.filter(public=True)), name='subject_index'),
    url(r'^new/$', views.SubjectCreate.as_view(), name="subject_create"),
    url(r'^(?P<pk>\w+)/edit/$', views.SubjectUpdate.as_view(), name="subject_edit"),
    url(r'^(?P<pk>\w+)/axis/$', views.EditAxis.as_view(), name='axis_edit'),
    url(r'^(?P<subject_id>\w+)/$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<subject_id>\w+)/practice/new/$', views.CreateView.as_view(), name='new'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/edit/$', views.UpdateView.as_view(), name='edit'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/duplicate/$', views.DuplicateView.as_view(), name='duplicate'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/delete/$', views.DeleteView.as_view(), name='delete'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/comment/$', views.CommentView.as_view(), name='comment'),
)

practishare/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.forms import PasswordResetForm
from django.views.generic import TemplateView
from practishare import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'practishare.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    
    url(r'^terms$', TemplateView.as_view(template_name="terms.html"), name='terms'),
    url(r'^support$', TemplateView.as_view(template_name="support.html"), name='support'),
    url(r'^subject/', include("practices.urls", namespace="practices")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
)

practishare/templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/practishare.css' %}">
        <title>{% block pagetitle %}{% endblock %} - Practishare</title>
        {% block scripts %}
        {% endblock %}
    </head>
    <body>
        <header class="container">
            <a href="/">
                <img id="logo" class="img-responsive" src="{% static 'logo.png' %}" />
                <img alt="Practishare" id="sitename" class="center-block" src="{% static 'practishare.png' %}" />
            </a>
            <nav class="text-center gray">
                <div class="col-md-4"><a href="http://www.practishare.com/pourquoi-faire">{% trans "What for" %}</a></div>
                <div class="col-md-4"><a href="{% url 'practices:subject_index' %}">{% trans "Subjects" %}</a></div>
                {% if user.is_authenticated %}
                <div class="col-md-4">{{user}} - <a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a></div>
                {% else %}
                <div class="col-md-4"><a href="{% url 'auth_login' %}?next={{request.path}}">{% trans "Log in" %}</a></div>
                {% endif %}
            </nav>
        </header>
        <div id="headersep" class="container-fluid bgblue">
            <div class="container">
                <div id="contenttitle" class="pull-left blue">
                    <h2>{% block contenttitle %}{% endblock %}</h2>
                </div>
            </div>
        </div>
        <section class="container">
            {% block content %}
            {% endblock %}
        </section>
        <footer class="bggray blue">
            <div class="container">
                <div class="col-md-3 text-center"><a href="http://www.practishare.com/qui-sommes-nous">{% trans "Who are we?" %}</a></div>
                <div class="col-md-3 text-center"><a href="http://www.practishare.com/conditions">{% trans "Terms of use" %}</a></div>
                <div class="col-md-3 text-center"><a href="http://www.practishare.com/contact">{% trans "Support" %}</a></div>
                <div class="col-md-3 text-center"><a href="http://www.practishare.com">{% trans "Blog" %}</a></div>
            </div>
        </footer>
    </body>
</html>

practishare/templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block pagetitle %}{% trans "News" %}{% endblock %}
{% block contenttitle %}{% trans "Practishare" %}{% endblock %}
{% block content %}
    <h2>{% trans "News" %}</h2>
    <a href="{% url 'practices:subject_index' %}">{% trans "Browse subjects" %}</a>

{% endblock %}

practishare/templates/support.html
{% extends 'base.html' %}
{% load i18n %}

{% block pagetitle %}{% trans "Support" %}{% endblock %}
{% block contenttitle %}{% trans "Support" %}{% endblock %}
{% block content %}
    <h2>{% trans "Support" %}</h2>
    Support
{% endblock %}

practishare/templates/terms.html
{% extends 'base.html' %}
{% load i18n %}

{% block pagetitle %}{% trans "Terms" %}{% endblock %}
{% block contenttitle %}{% trans "Terms" %}{% endblock %}
{% block content %}
    <h2>{% trans "Terms" %}</h2>
    Terms
{% endblock %}

practishare/templates/who_are_we.html
{% extends 'base.html' %}
{% load i18n %}

{% block pagetitle %}{% trans "Who are we?" %}{% endblock %}
{% block contenttitle %}{% trans "Who are we?" %}{% endblock %}
{% block content %}
    <h2>{% trans "Who are we?" %}</h2>
    Who are we?
{% endblock %}