practices/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView
from practices import views, models

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(queryset = models.Subject.objects.filter(public=True)), name='subject_index'),
    url(r'^new/$', views.SubjectCreate.as_view(), name="subject_create"),
    url(r'^(?P<pk>\w+)/edit/$', views.SubjectUpdate.as_view(), name="subject_edit"),
    url(r'^(?P<pk>\w+)/axis/$', views.EditAxis.as_view(), name='axis_edit'),
    url(r'^(?P<subject_id>\w+)/$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<subject_id>\w+)/practice/new/$', views.CreateView.as_view(), name='new'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/edit/$', views.UpdateView.as_view(), name='edit'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/duplicate/$', views.DuplicateView.as_view(), name='duplicate'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/delete/$', views.DeleteView.as_view(), name='delete'),
    url(r'^(?P<subject_id>\w+)/practice/(?P<pk>\d+)/comment/$', views.CommentView.as_view(), name='comment'),
)

practishare/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.forms import PasswordResetForm
from django.views.generic import TemplateView
from practishare import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'practishare.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    
    url(r'^terms$', TemplateView.as_view(template_name="terms.html"), name='terms'),
    url(r'^support$', TemplateView.as_view(template_name="support.html"), name='support'),
    url(r'^subject/', include("practices.urls", namespace="practices")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
)

practices/models.py
# -*- coding: utf-8 -*-
import uuid
from django.db import models

class Subject(models.Model):
    id = models.CharField(primary_key=True, max_length=32)
    title = models.CharField(max_length=50, verbose_name=u"Titre")
    public = models .BooleanField(default=True)
    author = models.ForeignKey('auth.User', default=1, verbose_name=u"Auteur") 
    def save(self, *args, **kwargs):
        if not self.id:
            self.id = uuid.uuid4().hex
            while Subject.objects.filter(id=self.id):
                self.id = uuid.uuid4().hex
        super(Subject, self).save(*args, **kwargs)
    
    def __unicode__(self):
        return self.title

class Field(models.Model):
    subject = models.ForeignKey('Subject', verbose_name=u"Sujet")
    name = models.CharField(max_length=50, verbose_name=u"Nom")
    def __unicode__(self):
        return self.name

class Axis(models.Model):
    subject = models.ForeignKey('Subject', verbose_name=u"Titre")
    title = models.CharField(max_length=50, verbose_name=u"Titre")
    def __unicode__(self):
        return self.title

class AxisValue(models.Model):
    axis = models.ForeignKey('Axis', verbose_name=u"Axes")
    name = models.CharField(max_length=50, verbose_name=u"Valeur")
    def __unicode__(self):
        return self.name

class Practice(models.Model):
    subject = models.ForeignKey(Subject, verbose_name=u"Sujet")
    title = models.CharField(max_length=50, verbose_name=u"Titre")
    author = models.ForeignKey('auth.User', verbose_name=u"Auteur")
    created = models.DateTimeField(auto_now_add=True, verbose_name=u"Crée")
    updated = models.DateTimeField(auto_now=True, verbose_name=u"Mis à jour")
    url = models.URLField(blank=True, null=True)
    def __unicode__(self):
        return self.title

class PracticeFieldValue(models.Model):
    practice = models.ForeignKey(Practice)
    field = models.ForeignKey(Field)
    value = models.TextField(blank=True)
    class Meta:
        unique_together = (("practice", "field"),)

class PracticeAxisValue(models.Model):
    practice = models.ForeignKey(Practice)
    axis = models.ForeignKey(Axis)
    value = models.ForeignKey(AxisValue)
    class Meta:
        unique_together = (("practice", "axis"),)

class Comment(models.Model):
    text = models.TextField()
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey('auth.User')
    practice = models.ForeignKey(Practice)

practices/forms.py
# -*- coding: utf-8 -*-
from django import forms
from practices.models import *

class PracticeForm(forms.ModelForm):
    class Meta:
        model = Practice
        exclude = ['author', 'subject']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class AxisForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AxisForm, self).__init__(*args, **kwargs)
        self.fields['axis'].widget = forms.HiddenInput()
        if kwargs.has_key('initial'):
            axisid = kwargs['initial']['axis']
        elif kwargs.has_key('instance'):
            axisid = kwargs['instance'].axis.id
        self.fields['value'] = forms.ModelChoiceField(queryset=AxisValue.objects.filter(axis=axisid), label=Axis.objects.get(pk=axisid).title)
        self.fields['value'].widget.attrs={ 'required': 'true' }

class FieldForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FieldForm, self).__init__(*args, **kwargs)
        self.fields['field'].widget = forms.HiddenInput()
        if kwargs.has_key('initial'):
            fieldid = kwargs['initial']['field']
        elif kwargs.has_key('instance'):
            fieldid = kwargs['instance'].field.id
        self.fields['value'] = forms.CharField(label=Field.objects.get(pk=fieldid).name)

practices/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse_lazy
from django.forms.models import model_to_dict, inlineformset_factory
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.views import generic
from practices.models import Practice, Subject, Comment, Axis, PracticeAxisValue, PracticeFieldValue, AxisValue, Field
from practices.forms import PracticeForm, CommentForm, AxisForm, FieldForm

### Mixins ###
class LoginRequiredMixin(object):
    u"""Ensures that user must be authenticated in order to access view."""
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

class MultipleFormMixin(object):
    """Adds multiple forms and formsets capability to a FormView"""
    def get_context_data(self, **kwargs):
        #for form views, add inline forms in the context
        if hasattr(self, 'object'):
            kwargs['forms'] = self.get_forms()
        return super(MultipleFormMixin, self).get_context_data(**kwargs)
        
    def form_valid(self, forms):
        """If the form is valid, save the associated models"""
        for form in forms:
            if self.object:
                if not form.instance.pk:
                    form.instance = self.object
                form.save()
            else:
                self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def get_forms(self, extra_forms=[]):
        form_class = self.get_form_class()
        return [self.get_form(form_class)] + extra_forms
    
    def post(self, request, *args, **kwargs):
        """Handles POST requests, instantiating a form instance with the passed
        POST variables and then checked for validity."""
        forms = self.get_forms()
        if all([form.is_valid() for form in forms]):
            return self.form_valid(forms)
        else:
            return self.form_invalid(forms[0])

class SubjectMixin(generic.base.ContextMixin):
    u"""Generic view inside a subject"""
    model = Practice
    form_class = PracticeForm
    def dispatch(self, *args, **kwargs):
        self.subject = get_object_or_404(Subject, pk=self.kwargs['subject_id'])
        return super(SubjectMixin, self).dispatch(*args, **kwargs)
    def get_context_data(self, **kwargs):
        """Adds the subject in the template context"""
        kwargs['subject'] = self.subject
        return super(SubjectMixin, self).get_context_data(**kwargs)
    def get_object(self, *args, **kwargs):
        u"""Checks that the practice is in the subject"""
        practice = super(SubjectMixin, self).get_object(*args, **kwargs)
        if practice.subject != self.subject:
            raise Http404
        return practice
    def get_success_url(self):
        u"""Returns to the subject view after form handling"""
        return reverse_lazy("practices:index", kwargs={'subject_id': self.subject.id})
    
    def get_forms(self, extra_forms=[]):
        """Generates formsets for the practice, depending on the subject"""
        # don't exclude practice if it's None, because it would exclude axis that don't have any practice yet
        # -1 is known to be an impossible value
        axis_list = map(lambda a: {'axis': a.id}, self.subject.axis_set.exclude(practiceaxisvalue__practice = self.object or -1))
        field_list = map(lambda f: {'field': f.id}, self.subject.field_set.exclude(practicefieldvalue__practice = self.object or -1))
        
        AxisFormSet = inlineformset_factory(Practice, PracticeAxisValue, can_delete=False, form=AxisForm, extra=len(axis_list), max_num=self.subject.axis_set.count())
        FieldFormSet = inlineformset_factory(Practice, PracticeFieldValue, can_delete=False, form=FieldForm, extra=len(field_list), max_num=self.subject.field_set.count())
        
        data = self.request.POST or None
        forms = [AxisFormSet(data, initial=axis_list, instance=self.object),
            FieldFormSet(data, initial=field_list, instance=self.object)] + extra_forms
        return super(SubjectMixin, self).get_forms(forms)
    
    def form_valid(self, forms):
        """If the form is valid, save the associated models"""
        forms[0].instance.subject = self.subject
        forms[0].instance.author = self.request.user
        return super(SubjectMixin, self).form_valid(forms)

### Definition of the actual views ###
class IndexView(SubjectMixin, generic.ListView):
    u"""Lists all the practices of a subject"""
    def get_queryset(self):
        return self.subject.practice_set.all()
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        axis = self.subject.axis_set.all()
        context['rows'] = axis[0].axisvalue_set.all()
        context['columns'] = axis[1].axisvalue_set.all()
        return context

class DetailView(SubjectMixin, generic.DetailView):
    u"""Shows the detail of a practice"""
    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context

class UpdateView(LoginRequiredMixin, SubjectMixin, MultipleFormMixin, generic.UpdateView):
    u"""Updates a practice"""
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(UpdateView, self).post(request, *args, **kwargs)

class CreateView(LoginRequiredMixin,SubjectMixin, MultipleFormMixin, generic.CreateView):
    u"""Creates a new practice"""
    def post(self, request, *args, **kwargs):
        self.object = None
        return super(CreateView, self).post(request, *args, **kwargs)

class DuplicateView(CreateView):
    u"""Creates a new practice as a copy of the given one"""
    def get_initial(self):
        practice = Practice.objects.get(pk = self.kwargs['pk'])
        practice.pk = None
        return model_to_dict(practice)
    
class DeleteView(LoginRequiredMixin, SubjectMixin, generic.DeleteView):
    u"""Deletes a given practice"""
    pass

class CommentView(LoginRequiredMixin, generic.CreateView):
    u"""Adds a comment on a practice"""
    model = Comment
    form_class = CommentForm
    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse_lazy("practices:detail", kwargs=kwargs))
    def get_success_url(self):
        return reverse_lazy("practices:detail", kwargs=self.kwargs)
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.practice_id = self.kwargs['pk']
        return super(CommentView, self).form_valid(form)

class BaseSubjectEdit(LoginRequiredMixin, MultipleFormMixin):
    u"""Base for edition of a subject"""
    model = Subject
    fields = ['title', 'public']
    def get_success_url(self):
        return reverse_lazy("practices:axis_edit", kwargs={"pk":self.object.id})
    
    def form_valid(self, forms):
        """If the form is valid, save the associated models"""
        forms[0].instance.author = self.request.user
        return super(BaseSubjectEdit, self).form_valid(forms)
    
    def get_forms(self, extra_forms=[]):
        AxisFormSet = inlineformset_factory(Subject, Axis, can_delete=False, extra=2, max_num=2)
        FieldFormSet = inlineformset_factory(Subject, Field, extra=1)
        data = self.request.POST or None
        forms = [AxisFormSet(data, instance=self.object),
            FieldFormSet(data, instance=self.object)] + extra_forms
        return super(BaseSubjectEdit, self).get_forms(forms)

class SubjectCreate(BaseSubjectEdit, generic.CreateView):
    u"""Creation of a subject"""
    def post(self, request, *args, **kwargs):
        self.object = None
        return super(SubjectCreate, self).post(request, *args, **kwargs)

class SubjectUpdate(BaseSubjectEdit, generic.UpdateView):
    u"""Modification of a subject"""
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(SubjectUpdate, self).post(request, *args, **kwargs)
    def get_object(self, queryset = None):
        subject = super(SubjectUpdate, self).get_object(queryset)
        if subject.author != self.request.user:
            raise PermissionDenied
        return subject

class EditAxis(LoginRequiredMixin, MultipleFormMixin, generic.UpdateView):
    u"""Edit a subject"""
    model = Subject
    fields = []
    def get_success_url(self):
        return reverse_lazy("practices:index", kwargs={"subject_id":self.object.id})
    
    def get_forms(self, extra_forms=[]):
        AxisValueFormSet = inlineformset_factory(Axis, AxisValue, extra=1)
        data = self.request.POST or None
        forms = [AxisValueFormSet(data, instance=axis, prefix="axis%s"%axis.id) for axis in self.object.axis_set.all()] + extra_forms
        return super(EditAxis, self).get_forms(forms)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(EditAxis, self).post(request, *args, **kwargs)

    def get_object(self, queryset = None):
        subject = super(EditAxis, self).get_object(queryset)
        if subject.author != self.request.user:
            raise PermissionDenied
        return subject

practices/templates/practices/index.html
{% if practices %}
    <ul>
    {% for practice in practices %}
        <li>
            <a href="{% url 'practices:detail' pk=practice.id %}">{{ practice.title }}</a>
            <a href="{% url 'practices:delete' pk=practice.id %}">Delete</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No practices are available.</p>
{% endif %}
<a href="{% url 'practices:new' %}">Add new</a>

practices/templates/practices/practice_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block pagetitle %}{% trans "Delete" %}{% endblock %}
{% block contenttitle %}{% trans "Delete" %}{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>{% blocktrans %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}</p>
    <input type="submit" value="{% trans 'Submit' %}" class="btn btn-action"/>
</form>
{% endblock %}

practices/templates/practices/practice_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block pagetitle %}{{ practice.title }}{% endblock %}
{% block contenttitle %}<a href="{% url 'practices:index' subject_id=subject.id %}">{{ subject.title }}</a>{% endblock %}
{% block content %}
<div class="pull-right">
    {% if user == practice.author or user == practice.subject.user %}
    <div><a href="{% url 'practices:edit' subject_id=subject.id pk=practice.id %}">{% trans "Edit" %}</a></div>
    {% endif %}
    <div><a href="{% url 'practices:duplicate' subject_id=subject.id pk=practice.id %}">{% trans "Duplicate" %}</a></div>
    <div><a href="mailto:?subject={{ subject.title }}&body=http://{{ request.META.HTTP_HOST }}{{ request.get_full_path }}">{% trans "Send by email" %}</a></div>
    <div>{% trans "Created on"%} {{ practice.created }}</div>
    <div>{% trans "Updated on"%} {{ practice.updated }}</div>
</div>

<div class="center-block practice">
    <div class="bgblue white practice-header">
        <div class="practice-author">{{ practice.author }}</div>
        <div class="text-center"><b>{{ practice.title }}</b></div>
    </div>
    <div>
        {% for axisvalue in practice.practiceaxisvalue_set.all %}
        <div class="col-md-6 text-center practice-axis">{{ axisvalue.value }}</div>
        {% endfor %}
    </div>
    <div class="clearfix"></div>
    
    <div class="practice-content">
        {% for fieldvalue in practice.practicefieldvalue_set.all %}
        <p>
            <span class="blue">{{ fieldvalue.field }}:</span>
            {{ fieldvalue.value }}
        </p>
        {% endfor %}
        <p>
            <span class="blue">{% trans "URL" %}:</span>
            <a target="_blank" href="{{ practice.url }}">{{ practice.url }}</a>
        </p>
    </div>
    <div class="clearfix"></div>
</div>
<div id="comments" class="center-block">
    <div class="bgblue white practice-header">
        {% trans "Comments" %}
    </div>
    {% for comment in practice.comment_set.all %}
    <div class="comment">
        {{comment.author}} {% trans "on" %} {{comment.date}} :
        {{comment.text}}
    </div>
    {% endfor %}
    {% if user.is_authenticated %}
    <form action="{% url 'practices:comment' subject_id=subject.id pk=practice.id %}" method="POST">
        {% csrf_token %}
        <label for="{{ comment_form.text.id_for_label }}">{% trans "Add a comment" %}</label>
        {{comment_form.text}}
        <input type="submit" value="{% trans 'Submit' %}" />
    </form>
    {% else %}
    {% trans "Please" %} <a href="{% url 'auth_login' %}">{% trans "Log in" %}</a> {% trans "to comment this practice." %}
    {% endif %}
</div>
{% endblock %}

practices/templates/practices/practice_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap %}

{% block pagetitle %}{{ practice.title | default:_("New good practice") }}{% endblock %}
{% block contenttitle %}{{ practice.title | default:_("New good practice") }}{% endblock %}
{% block content %}
<form class="form-horizontal" action="" method="post">
    {% csrf_token %}
    {% for form in forms %}
        {{form|bootstrap_horizontal}}
    {% endfor %}
    <div class="btn-toolbar">
        <span class="btn btn-action" onclick="window.history.back();return false">{% trans 'Cancel' %}</span>
        <input type="submit" value="{% trans 'Submit' %}" class="btn btn-action"/>
    </div>
</form>
{% endblock %}

practices/templates/practices/practice_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load practices %}

{% block pagetitle %}{{ subject.title }}{% endblock %}
{% block contenttitle %}{{ subject.title }}{% endblock %}
{% block content %}

{% if practice_list %}
<div class="center-block">
    <table class="table table-striped practice-table">
        <tr>
            <th></th>
            {% for column in columns %}
            <th>{{column}}</th>
            {% endfor %}
        </tr>
        {% for row in rows %}
        <tr>
            <th>{{row}}</th>
            {% with practice_list|filterbyaxis:row as practices %}
                {% for column in columns %}
                    <td>
                    {%for practice in practices|filterbyaxis:column %}
                        <a href="{% url 'practices:detail' subject_id=subject.id pk=practice.id %}" title="{{practice.title}}" alt="{{practice.title}}">
                        <img src="{% static 'icone.png' %}" class="icone" alt="icone"/>
                        </a>
                    {% endfor %}
                    </td>
                {% endfor %}
            {% endwith %}
        </tr>
        {% endfor %}
    </table>
</div>
{% else %}
    <p>Pas de pratiques disponibles.</p>
{% endif %}
<a href="{% url 'practices:new' subject_id=subject.id %}"><span class="btn btn-action">{% trans "Ajouter une bonne pratique" %}</span></a><br/><br/>

{% if user == subject.author %}
<a href="{% url 'practices:subject_edit' pk=subject.id %}"><span class="btn btn-action">{% trans "Modifier ce sujet" %}</span></a>
{% endif %}

{% endblock %}

practices/templates/practices/subject_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap %}

{% block pagetitle %}{{ subject.title | default:_("Nouveau Sujet") }}{% endblock %}

{% block contenttitle %}{{ subject.title | default:_("Nouveau Sujet") }}{% endblock %}

{% block scripts %}
<script type="text/javascript">
    function addForm(newFormDiv, targetDiv) { 
        var formIdx = targetDiv.querySelector('[id$=TOTAL_FORMS]').value;
        var newForm = document.createElement('div');
        newForm.innerHTML = newFormDiv.innerHTML.replace(/__prefix__/g, formIdx);
        while (newForm.firstChild) targetDiv.appendChild(newForm.firstChild);
        targetDiv.querySelector('[id$=TOTAL_FORMS]').value = parseInt(formIdx) + 1;
    }
</script>
{% endblock %}

{% block content %}

<h3>Création de votre practishare :</h3>

<p>Ce formulaire vous permet de configurer votre practishare en deux temps, en indiquant :</p> 

<ul>
    <li>un titre, les noms des 2 axes de votre tableau ainsi que les champs qui décrivent une pratique</li>
    <li>dans l'écran suivant, vous pourrez indiquer les valeurs des axes (entêtes du tableau).</li>
    
</ul>
    <p>Vous pourrez modifier cette configuration ultérieurement ("modifier le sujet")</p>
    <p>Si vous souhaitez que ce practishare ne soit pas public, décochez la case correspondante, sous le titre. Conservez alors précieusement le lien qui sera généré.</p>

<form class="form-horizontal" action="" method="post">
    {% csrf_token %}
    {% for form in forms %}
    {% if form.prefix = 'title' %}<h2 class="title-border">Titre du sujet</h2>{% endif %}

        {% if form.prefix = 'axis_set' %}<h2 class="title-border">Axes</h2>

        {% elif form.prefix = 'field_set' %}<h2 class="title-border">Champs</h2>

        {% elif form.prefix|slice:':4' = 'axis' %}

        <h2 class="title-border"> {{ form.instance.title}} </h2>

        {% endif %}
        <div>
            {{form|bootstrap_horizontal}}
        </div>
        {% if form.max_num > 2 %}
        <button type='button' onclick="addForm(this.nextElementSibling, this.previousElementSibling)" class="btn-action add-btn">Ajouter</button>
        <div style="display:none">
            <div class="clearfix"></div>
            {{ form.empty_form|bootstrap_horizontal }}
        </div>
        {% endif %}

    {% endfor %}

    <div class="btn-toolbar">
        <span class="btn btn-action" onclick="window.history.back();return false">{% trans 'Cancel' %}</span>
        <input type="submit" value="{% trans 'Submit' %}" class="btn btn-action"/>
    </div>
</form>
{% endblock %}

practices/templates/practices/subject_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block pagetitle %}{% trans "Subjects" %}{% endblock %}
{% block contenttitle %}{% trans "Subjects" %}{% endblock %}
{% block content %}

{% if subject_list %}
    <ul>
    {% for subject in subject_list %}
        <li>
            <a href="{% url 'practices:index' subject_id=subject.id %}">{{ subject.title }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No subjects are available.</p>
{% endif %}
    <a href="{% url 'practices:subject_create'  %}"><span class="btn btn-action">Ajouter un sujet</span></a>
{% endblock %}